### ISSUE TITLE
error when attempting to run bash irecovery

### ISSUE THREAD

**Issue by bhutapat4** [libimobiledevice/libirecovery#35] opened 2017-10-10 23:59 UTC
irecovery: error while loading shared libraries: libirecovery.so.2: cannot open shared object file

**Comment by nikias** [comment] 2017-10-11 01:10
This is not a bug but a failure in properly installing irecovery and the corresponding library. Have you tried running ldconfig?
Closing since this is not a bug.

**Closed by nikias** 2017-10-11 01:10 UTC
